{
//=========Macro generated from canvas: c1/c1
//=========  (Sat Mar  7 16:17:57 2015) by ROOT version5.34/18
   TCanvas *c1 = new TCanvas("c1", "c1",10,32,1169,969);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTicky(1);
   c1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: mpad
   TPad *mpad = new TPad("mpad", "mpad",0.01,0.01,0.99,0.99);
   mpad->Draw();
   mpad->cd();
   mpad->Range(3.896104,0.2050633,10.38961,0.8379747);
   mpad->SetFillColor(0);
   mpad->SetBorderMode(0);
   mpad->SetBorderSize(0);
   mpad->SetGridy();
   mpad->SetTicky(1);
   mpad->SetLeftMargin(0.17);
   mpad->SetRightMargin(0.06);
   mpad->SetTopMargin(0.06);
   mpad->SetBottomMargin(0.15);
   mpad->SetFrameBorderMode(0);
   mpad->SetFrameBorderMode(0);
   
   TH2F *hfr = new TH2F("hfr"," ",10,5,10,10,0.3,0.8);
   hfr->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   hfr->SetLineColor(ci);
   hfr->SetMarkerSize(1.6);
   hfr->GetXaxis()->SetTitle("power law exp. n  ");
   hfr->GetXaxis()->CenterTitle(true);
   hfr->GetXaxis()->SetNdivisions(505);
   hfr->GetXaxis()->SetLabelFont(42);
   hfr->GetXaxis()->SetLabelOffset(0.01);
   hfr->GetXaxis()->SetLabelSize(0.05);
   hfr->GetXaxis()->SetTitleSize(0.06);
   hfr->GetXaxis()->SetTitleOffset(1.1);
   hfr->GetXaxis()->SetTitleFont(42);
   hfr->GetYaxis()->SetTitle("#LTz#GT");
   hfr->GetYaxis()->CenterTitle(true);
   hfr->GetYaxis()->SetNdivisions(505);
   hfr->GetYaxis()->SetLabelFont(42);
   hfr->GetYaxis()->SetLabelOffset(0.001);
   hfr->GetYaxis()->SetLabelSize(0.05);
   hfr->GetYaxis()->SetTitleSize(0.06);
   hfr->GetYaxis()->SetTitleOffset(1.1);
   hfr->GetYaxis()->SetTitleFont(42);
   hfr->GetZaxis()->SetLabelFont(42);
   hfr->GetZaxis()->SetLabelSize(0.035);
   hfr->GetZaxis()->SetTitleSize(0.035);
   hfr->GetZaxis()->SetTitleFont(42);
   hfr->Draw("");
   
   TF1 *fz = new TF1("fz","(TMath::Gamma(x,[0])*TMath::Gamma(x))/(TMath::Gamma(x-1,[0])*TMath::Gamma(x-1))/[0]",5,10);
   fz->SetFillColor(19);
   fz->SetFillStyle(0);
   fz->SetMarkerSize(1.6);
   fz->SetLineColor(2);
   fz->SetLineWidth(2);
   fz->GetXaxis()->SetLabelFont(42);
   fz->GetXaxis()->SetLabelSize(0.035);
   fz->GetXaxis()->SetTitleSize(0.035);
   fz->GetXaxis()->SetTitleFont(42);
   fz->GetYaxis()->SetLabelFont(42);
   fz->GetYaxis()->SetLabelSize(0.035);
   fz->GetYaxis()->SetTitleSize(0.035);
   fz->GetYaxis()->SetTitleFont(42);
   fz->SetParameter(0,8.5);
   fz->SetParError(0,0);
   fz->SetParLimits(0,0,0);
   fz->Draw("same");
   TLine *line = new TLine(6.5,0.3,6.5,0.5807456);
   line->SetLineStyle(2);
   line->Draw();
   line = new TLine(8.2,0.3,8.2,0.691236);
   line->SetLineStyle(2);
   line->Draw();
   
   TF1 *fz = new TF1("fz","(TMath::Gamma(x,[0])*TMath::Gamma(x))/(TMath::Gamma(x-1,[0])*TMath::Gamma(x-1))/[0]",5,10);
   fz->SetFillColor(19);
   fz->SetFillStyle(0);
   fz->SetMarkerSize(1.6);
   fz->SetLineColor(2);
   fz->SetLineWidth(2);
   fz->SetLineStyle(2);
   fz->GetXaxis()->SetLabelFont(42);
   fz->GetXaxis()->SetLabelSize(0.035);
   fz->GetXaxis()->SetTitleSize(0.035);
   fz->GetXaxis()->SetTitleFont(42);
   fz->GetYaxis()->SetLabelFont(42);
   fz->GetYaxis()->SetLabelSize(0.035);
   fz->GetYaxis()->SetTitleSize(0.035);
   fz->GetYaxis()->SetTitleFont(42);
   fz->SetParameter(0,11.5);
   fz->SetParError(0,0);
   fz->SetParLimits(0,0,0);
   fz->Draw("same");
   
   TLegend *leg = new TLegend(0.45,0.2,0.72,0.35,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL"," ","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("fz","quark","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("fz","gluon","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(8.328717,0.4318404,"RHIC");
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(6.633819,0.4275868,"LHC");
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   mpad->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
   c1->ToggleToolBar();
}
